#!/usr/bin/env python
from textwrap import wrap

import click

from engine.answers import ask


@click.command()
@click.option(
    "-c",
    "--collection",
    help="Name of the collection to search",
    default="SEIU-contracts",
)
@click.option(
    "-m",
    "--model",
    help="Name of the LLM model to use",
    default="default",
)
@click.option("-t", "--topic", help="Topic related to the query", default="")
@click.option("-v", "--verbose", help="Enable verbose mode", is_flag=True)
@click.argument("query")
def main(collection, query, model, topic, verbose):

    # Call the ask function from the engine.answers module
    think, answer, seq, seconds = ask(
        query = query,
        topic = topic,
        user = "Developer",
        model = model,
        collection_name=collection,
    )

    # Print the topic, sequence number, and query
    print(f"Topic: {topic} [{seq}]")
    print("Query:")
    for line in wrap(query):
        print(f"  {line}")

    # If verbose mode is enabled, print the thinking process
    if verbose:
        print("Think:")
        for t in think:
            for line in wrap(t):
                print(f"  {line}")
            print()

    # Print the answer(s)
    print("Answer:")
    for a in answer:
        for line in wrap(a):
            print(f"  {line}")
        print()

    # Print the time taken to compute the answer
    print(f"Answer computed in {seconds:,} seconds with model '{model}'")


if __name__ == "__main__":
    main()
