#!/usr/bin/env python
"""
Find the best matching fragments for a given query.
"""

import click

from engine.answers import search_fragments


@click.command()
@click.option(
    "-n",
    "--num-results",
    default=5,
    type=int,
    help="Maximum number of results to return.",
)
@click.option(
    "-m",
    "--max-distance",
    default=1.0,
    type=float,
    help="Maximum distance for matching fragments.",
)
@click.option(
    "-c",
    "--collection",
    help="Name of the collection to search",
    default="SEIU-contracts",
)
@click.argument("query")
def main(query: str, num_results: int, max_distance: float, collection: str) -> None:
    results = search_fragments(query, num_results, collection_name=collection)
    for result in results:
        if result.distance <= max_distance:
            print(f"Distance {result.distance:.2f}")
            print(result.doc.strip())
            print("-----")


if __name__ == "__main__":
    main()
