name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:      
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add secrets to repository checkout
        env:
          credentials: ${{ secrets.credentials }}
        run: |
          mkdir -p secrets
          echo "${credentials}" > secrets/credentials
          chmod 600 secrets/credentials

      - name: Deploy to main
        if: github.ref == 'refs/heads/main'
        env:
          INSTANCE: ec2-user@bossbot.org
        run: |
          rsync -a $PWD $INSTANCE:/home/ec2-user --delete
          ssh -o StrictHostKeyChecking=no $INSTANCE -t 'bash -l -c "
              cd $HOME/BossBot
              bin/make-certs
              ./deploy.sh
          "'
