name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:      
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add secrets to repository checkout
        env:
          engines_json: ${{ secrets.engines_json }}
        run: |
          mkdir -p secrets
          echo "$engines_json" > secrets/engines.json

      - name: Generate certificates
        run: |
          bin/make-certs

      - name: Deploy to main
        if: github.ref == 'refs/heads/main'
        env:
          INSTANCE: ec2-user@bossbot.org
        run: |
          rsync -a $PWD $INSTANCE:/home/ec2-user --delete
          ssh -o StrictHostKeyChecking=no $INSTANCE -t 'bash -l -c "
              cd $HOME/BossBot
              if ./deploy.sh check; then
                 ./deploy.sh serve
              else
                 exit 1
              fi
          "'
